FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libsdl2-dev libfreetype6-dev libportmidi-dev libavformat-dev libswscale-dev libsmpeg-dev libjpeg-dev libtiff-dev libx11-dev libxext-dev libxrandr-dev libxss-dev libxi-dev \
    && apt-get clean

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "main.py"]
