services:
  - type: web
    name: spatial-game
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars: 
    buildCommand: |
  apt-get update && apt-get install -y \
    libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
    libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libfreetype6-dev
  pip install -r requirements.txt
